name: Python

on: [push, pull_request]

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install PyLint
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run PyLint
      run: pylint -j$(nproc) $(git ls-files '*.py')
